"""set verification code to not unique

Revision ID: 0177cd468e81
Revises: 97cd97a242e1
Create Date: 2023-10-31 10:03:52.551214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0177cd468e81'
down_revision = '97cd97a242e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_verification_code_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_verification_code_key', 'users', ['verification_code'])
    # ### end Alembic commands ###
