"""added pet table, pet type, and pet images and modify users table

Revision ID: 0468eb7f919a
Revises: 4917da928a79
Create Date: 2023-10-26 11:43:42.524764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0468eb7f919a'
down_revision = '4917da928a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('microchip_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('behavior', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('pet_type_id', sa.Integer(), nullable=True),
    sa.Column('main_picture', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('date_of_birth_month', sa.Integer(), nullable=True),
    sa.Column('date_of_birth_year', sa.Integer(), nullable=True),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_type_id'], ['pet_type.type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_microchip_id'), 'pets', ['microchip_id'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_table('pet_images',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id', 'pet_id')
    )
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('secondary_contact', sa.String(), nullable=True))
    op.add_column('users', sa.Column('secondary_contact_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'secondary_contact_number')
    op.drop_column('users', 'secondary_contact')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'country')
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'state_code')
    op.drop_column('users', 'city')
    op.drop_column('users', 'city_code')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'street_address')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_table('pet_images')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index(op.f('ix_pets_microchip_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_table('pet_type')
    # ### end Alembic commands ###
