"""revised pettype models

Revision ID: 265a4051c3b7
Revises: 290c83a32bdc
Create Date: 2023-11-04 03:33:39.676293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265a4051c3b7'
down_revision = '290c83a32bdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pet_type', ['type'])
    op.create_unique_constraint(None, 'pet_type', ['type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet_type', type_='unique')
    op.drop_constraint(None, 'pet_type', type_='unique')
    # ### end Alembic commands ###
