"""modified pet table; added json column allergies, medication, and vaccines

Revision ID: 2aa2a8c3021f
Revises: bb79086d09ad
Create Date: 2024-04-08 15:43:28.179538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa2a8c3021f'
down_revision = 'bb79086d09ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.add_column('pets', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('pets', sa.Column('medications', sa.JSON(), nullable=True))
    op.add_column('pets', sa.Column('vaccines', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'vaccines')
    op.drop_column('pets', 'medications')
    op.drop_column('pets', 'allergies')
    op.drop_constraint(None, 'notifications', type_='unique')
    # ### end Alembic commands ###
