"""updated user table; added column settings, settings setter and getter

Revision ID: 3b41d6a5ddfc
Revises: 2aa2a8c3021f
Create Date: 2024-04-09 01:23:38.655562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b41d6a5ddfc'
down_revision = '2aa2a8c3021f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
