"""added pet table, pet type, and pet images and modify users table

Revision ID: 3f84bda6ebef
Revises: 0468eb7f919a
Create Date: 2023-10-26 12:00:24.095931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f84bda6ebef'
down_revision = '0468eb7f919a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pet_type', ['type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet_type', type_='unique')
    # ### end Alembic commands ###
