"""added otp created date 

Revision ID: 45b7ed09b10b
Revises: f0974aab788d
Create Date: 2023-11-27 02:23:26.796518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b7ed09b10b'
down_revision = 'f0974aab788d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_created_at')
    # ### end Alembic commands ###
