"""added column image_urls in product table

Revision ID: 46299abbfc11
Revises: a99a41a4554f
Create Date: 2024-03-07 16:43:51.619329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46299abbfc11'
down_revision = 'a99a41a4554f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'products', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###
