"""change table name from QRScan into ScanHistory

Revision ID: 699a077cc1e5
Revises: 9a51849816d0
Create Date: 2024-04-04 11:13:44.802304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '699a077cc1e5'
down_revision = '9a51849816d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('qr_code_id', sa.String(), nullable=True),
    sa.Column('scanned_by', sa.String(), server_default='Anonymous', nullable=True),
    sa.Column('scan_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('scan_result', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_scan_history_qr_code_id'), 'scan_history', ['qr_code_id'], unique=False)
    op.drop_index('ix_qr_scans_qr_code_id', table_name='qr_scans')
    op.drop_table('qr_scans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scans',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('qr_code_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scanned_by', sa.VARCHAR(), server_default=sa.text("'Anonymous'::character varying"), autoincrement=False, nullable=True),
    sa.Column('scan_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scan_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='qr_scans_pkey'),
    sa.UniqueConstraint('id', name='qr_scans_id_key')
    )
    op.create_index('ix_qr_scans_qr_code_id', 'qr_scans', ['qr_code_id'], unique=False)
    op.drop_index(op.f('ix_scan_history_qr_code_id'), table_name='scan_history')
    op.drop_table('scan_history')
    # ### end Alembic commands ###
