"""change server default value for created and update date of pets

Revision ID: 76ae04625217
Revises: 8cd29949f356
Create Date: 2023-12-20 07:44:16.730149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ae04625217'
down_revision = '8cd29949f356'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'pets', ['unique_id'])
    op.alter_column('pets', 'unique_id', existing_type=sa.String(), nullable=False, unique=True)
    op.alter_column('pets', 'updated_at', existing_type=sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True)
    op.alter_column('pets', 'created_at', existing_type=sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'pets', type_='unique')
    # ### end Alembic commands ###
    
    op.alter_column('pets', 'unique_id', existing_type=sa.String(), nullable=False, unique=False)
    op.alter_column('pets', 'created_at', existing_type=sa.TIMESTAMP(timezone=True), server_default=None, nullable=False)
    op.alter_column('pets', 'updated_at', existing_type=sa.TIMESTAMP(timezone=True), server_default=None, nullable=False)
