"""added display flag and status flag on feedback and users column respectively

Revision ID: 8cd29949f356
Revises: 4371d3b80280
Create Date: 2023-12-12 16:44:46.482125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd29949f356'
down_revision = '4371d3b80280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('display_flag', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'pet_type', ['type'])
    op.create_foreign_key(None, 'pets', 'pet_type', ['pet_type_id'], ['type_id'])
    op.add_column('users', sa.Column('status', sa.String(), server_default='active', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'status')
    # op.drop_constraint(None, 'pets', type_='foreignkey')
    # op.drop_constraint(None, 'pet_type', type_='unique')
    # op.drop_column('feedback', 'display_flag')
    # ### end Alembic commands ###
