"""change owners to owner in pet models

Revision ID: 97cd97a242e1
Revises: abe174fa1213
Create Date: 2023-10-27 11:18:27.989119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cd97a242e1'
down_revision = 'abe174fa1213'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
