"""added no_of_scans column in pet table

Revision ID: 9a51849816d0
Revises: a0c3a6095e34
Create Date: 2024-04-04 10:51:23.507796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a51849816d0'
down_revision = 'a0c3a6095e34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('no_of_scans', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'qr_scans', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_scans', type_='unique')
    op.drop_column('pets', 'no_of_scans')
    # ### end Alembic commands ###
