"""modify table user and pet

Revision ID: 9c448951d358
Revises: 3f84bda6ebef
Create Date: 2023-10-26 12:08:54.099036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c448951d358'
down_revision = '3f84bda6ebef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
