"""added QRScan table

Revision ID: a0c3a6095e34
Revises: 46299abbfc11
Create Date: 2024-04-04 10:47:03.488283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0c3a6095e34'
down_revision = '46299abbfc11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('qr_code_id', sa.String(), nullable=True),
    sa.Column('scanned_by', sa.String(), server_default='Anonymous', nullable=True),
    sa.Column('scan_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('scan_result', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_qr_scans_qr_code_id'), 'qr_scans', ['qr_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_scans_qr_code_id'), table_name='qr_scans')
    op.drop_table('qr_scans')
    # ### end Alembic commands ###
