"""modify table user and pet

Revision ID: abe174fa1213
Revises: 9c448951d358
Create Date: 2023-10-26 12:10:52.382064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe174fa1213'
down_revision = '9c448951d358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
