"""added reset tokens for reset password

Revision ID: b160ac2988e9
Revises: 5e4ef135a2e5
Create Date: 2024-01-02 15:16:50.214825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b160ac2988e9'
down_revision = '5e4ef135a2e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_reset_tokens_token'), 'reset_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_token'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    # ### end Alembic commands ###
